name: Build & Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: threeal/cmake-action@v2
      - name: Test
        uses: threeal/ctest-action@v1
